// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtqfrzsyctjmxpcegktd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cWZyenN5Y3RqbXhwY2Vna3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MTU4MzEsImV4cCI6MjA1MTM5MTgzMX0.X0MF25vAjsaPZfX_i97_gdco0xcPaT0vtLmXrp43NUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);